def kebab(s: str) -> str: ...
def lower_camel(s: str) -> str: ...
def shouty_kebab(s: str) -> str: ...
def shouty_snake(s: str) -> str: ...
def snake(s: str) -> str: ...
def title(s: str) -> str: ...
def upper_camel(s: str) -> str: ...
