from typing import Sequence

def snake(s: str) -> str: ...
def snake_many(strings: Sequence[str]) -> list[str]: ...
def lower_camel(s: str) -> str: ...
def lower_camel_many(strings: Sequence[str]) -> list[str]: ...
def title(s: str) -> str: ...
def title_many(strings: Sequence[str]) -> list[str]: ...
def upper_camel(s: str) -> str: ...
def upper_camel_many(strings: Sequence[str]) -> list[str]: ...
def kebab(s: str) -> str: ...
def kebab_many(strings: Sequence[str]) -> list[str]: ...
def shouty_kebab(s: str) -> str: ...
def shouty_kebab_many(strings: Sequence[str]) -> list[str]: ...
def shouty_snake(s: str) -> str: ...
def shouty_snake_many(strings: Sequence[str]) -> list[str]: ...
